#!/usr/bin/env bash

# Get highest resolution and refresh rate from xrandr
output="$(xrandr --query | grep ' connected' | cut -d' ' -f1)"
line="$(xrandr --query | grep -A1 "^$output" | tail -1 | tr -d '+*' | tr -s ' ' | cut -c 2-)"
mode="$(echo "$line" | cut -d' ' -f1)"
rate="$(echo "$line" | cut -d' ' -f2- | tr ' ' '\n' | sort -nr | head -1)"

# Set resolution and refresh rate
xrandr --output "$output" --mode "$mode" --rate "$rate"
# Disable DPMS (Monitor turning off after inactivity)
xset s off -dpms
# Set autorepeat rate to match tty
xset r rate 300 50

screen_height="$(echo "$mode" | cut -dx -f2)"

font_text='JetBrains Mono NF'
font_icons='Font Awesome 6 Free Solid'
font_size="$((screen_height / 70))"
border="$((screen_height / 300))"

export POLYBAR_FONT_TEXT="$font_text:size=$font_size;$((screen_height / 275))"
export POLYBAR_FONT_ICONS="$font_icons:size=$font_size;$((screen_height / 275))"
export POLYBAR_BORDER="$border"

cat << EOF | xrdb -merge
I3_BORDER: $border
I3_GAPS:   $((screen_height / 50))
EOF

# Reload background
"$XDG_STATE_HOME/fehbg"
# Launch window manager
i3
