#!/usr/bin/env bash

# Create desktops
bspc monitor --reset-desktops 1 2 3 4 5 6 7 8 9 10

# Change focus on click with any mouse button
bspc config click_to_focus any
# Disable windows stealing focus
bspc config ignore_ewmh_focus true

# Appearance
bspc config window_gap "$GAP_SIZE"
bspc config border_width "$BORDER_SIZE"
bspc config normal_border_color \#1E1E2E
bspc config focused_border_color \#CDD6F4

# Disable default X cursor
xsetroot -cursor_name left_ptr

# Start hotkey daemon
pkill sxhkd; sxhkd &
# Start compositor
picom &
# Start bar
eww open bar_bspwm
# Reload wallpaper
[ -e "$XDG_STATE_HOME/fehbg" ] && "$XDG_STATE_HOME/fehbg"
