require("options")
require("keymaps")

require("plugins.colorscheme")

require("plugins.bufferline")
require("plugins.colors")
require("plugins.completion")
require("plugins.copilot")
require("plugins.folds")
require("plugins.git")
require("plugins.indents")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.none-ls")
require("plugins.pairs")
require("plugins.telescope")
require("plugins.treesitter")
