require("options")
require("keymaps")
require("autocmds")

require("plugins.colors")
require("plugins.completion")
require("plugins.copilot")
require("plugins.git")
require("plugins.lsp")
require("plugins.misc")
require("plugins.telescope")
require("plugins.treesitter")
