require("options")
require("keymaps")
require("autocmds")

-- Plugins
require("plugins.colorscheme")
require("plugins.colorizer")
require("plugins.completion")
require("plugins.copilot")
require("plugins.git")
require("plugins.lsp")
require("plugins.none-ls")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.misc")
