#!/usr/bin/env bash

. ~/.config/bash/env.sh
. ~/.config/bash/aliases.sh

# Enable fzf integration
eval "$(fzf --bash)"

set -o noclobber # Prevent implicit overwritting with redirection
shopt -s autocd  # Change directory without cd
shopt -s dotglob # Show hidden files during completion
shopt -s extglob # Enable additional globbing syntax

# Disable autocd output by redirecting xtrace
_hide_xtrace() { exec {BASH_XTRACEFD}>/dev/null; }
_show_xtrace() { exec {BASH_XTRACEFD}>/dev/stdout; }
[[ $- != *x* ]] && _hide_xtrace

# History
# ignoreboth: Don't save commands that start with a space or duplicates
# erasedups: Erase previous duplicates
HISTCONTROL=ignoreboth:erasedups
# Append history instead of overwritting it
shopt -s histappend

# Open app launcher with Alt + R
bind -x '"\er": app-launcher'

# Change directory with Yazi
f() {
  local tmp cwd
  tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
  yazi "$@" --cwd-file "$tmp"
  if cwd="$(command cat -- "$tmp")" && [[ -n "$cwd" ]] && [[ "$cwd" != "$PWD" ]]; then
    \cd "$cwd" || exit
  fi
  \rm "$tmp"
}

. ~/.config/bash/prompt.sh
